---
title: "Assessment Lotteries"
author: "Experiments in Assessment WG"
date: "2025-02-18"
categories: [news, code, analysis]
description: "This is a sample abstract description of an idea, to appear also in the listing page. This is a sample abstract description of an idea, to appear also in the listing page."
---

# Related CoARA commitments

# Idea introduction

What is the experiment? 

# Research domain(s)

- Which research domain does this idea apply to?
- Who is this for? (tags – use CoARA typology or something else that exists) 


# Concrete objectives

What are the vocrete objective/goals? What are we trying to change?

# Implementation suggestions

- Suggestions on how to implement (including research culture aspects) 
- Costs to consider for institutions for implementing the experiment (framed as questions) 

# Challenges and mitigations
Challenges and mitigation discussion (Questions to address or discuss) 

# Assessment criteria

How to ve assess the effects and outcomes (including “data”)  (related to goals)? 


# Relevant resources and examples

Possibly comments/lived examples
 
# !!! To be structered yet !!!
- Which questions/challenge does this answer? (which section is it in) 
