---
title: "CoARA Assessment Idea Catalogue"
listing:
  contents: ideas
  sort: "date desc"
  type: grid
  categories: true
  sort-ui: false
  filter-ui: false
  image-height: 0px
page-layout: full
title-block-banner: true
---
The **CaARA Assessment Idea Catalogue** is designed to be a resource for those developing and/or implementing assessment processes at a variety of different levels, including:

- hiring and promotion
- project funding
- research programme funding
- institutional evaluations 
- national research system evaluations. 

A collection of different experimental ideas are represented here, that can be used as inspiration for designing experiments that innovate on current assessment practices.

For information on how to use this catalogue, please look at the [Idea Catalogue How-To Guide](/how_to.qmd)

We welcome all feedback on the platform! To send us any feedback or ideas, please use the [Idea Catalogue Feedback Form](https://forms.gle/NkiTKMdTfpgzpwki7).  
  
If you would like to **submit a new idea** to the catalogue, please use [this form](https://forms.gle/6F4mPmHYa8dP9eVg9){target="_blank"}
