---
title: "Evaluating negative and null results"
author: "Experiments in Assessment WG"
date: last-modified
categories: [Level 2, CoARA Commitment 1, CoARA Commitment 3, CoARA Commitment 6, Challenge - Process, Challenge - Bias Mitigation, Challenge - Process Culture, Challenge - Diversity, User - Funder, User - Institutes, User - Meta-Researchers, User - Scientific editors and publishers]
description: "Evaluating negative and null results is a way to give visibility to the important learnings that come with experiments that did not yiels the expected findings. Allowing researchers to share null and negative results shifts the focus from outcomes to the research process, promoting learning, rigor, and integrity. It highlights skills, collaboration, and data transparency—even with inconclusive findings."
image: false
---

<!--
GENERAL GUIDELINES:
- Use this guide to style all text: https://quarto.org/docs/authoring/markdown-basics.html
- Tags (apply as relevant):
Level 0 = Level of completeness: 0 – The experiment only contains the description and minimal details. This level is meant to provide inspiration for experiments that can be developed further by those experimenting.
Level 1 = Level of completeness: 1 –  The experiment contains minimal details. Organisations will need to build the experimentation plan before they can implement the idea.
Level 2 = Level of completeness: 2 – The experiment contains minimal details that may help with the design and implementation, but organisations will need to build most of the experimentation plan before they can fully implement the idea.
Level 3 = Level of completeness: 3 – The experiment contains some details that may help with the design and implementation, but organisations will need to finalise the experimentation plan before they can fully implement the idea.
Level 4 = Level of completeness: 4 – The experiment contains details that can provide useful guidance for implementation, but additional research will need to be done by experimenting organisation. Few real life cases exist. 
Level 5 = Level of completeness: 5 – The experiment contains sufficient details to be implemented, and it has already been experimented in some organisations providing cases, additional suggestions, and often learned lessons. 
Challenge - Process = Create an assessment process based upon what the different players in research value
Challenge - Inclusivity = Make research more inclusive and equitable through assessment
Challenge - Bias Mitigation = Mitigate the negative effects of bias on assessment
Challenge - Process Culture = Recognize process and culture through assessment
Challenge - Diversity = Foster diversity through assessment
Challenge - Collaboration = Foster collaboration through assessment
Challenge - Different Questions = Ask assessment questions differently
CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 = Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 3 = Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index
CoARA Commitment 4 = Avoid the use of rankings of research organisations in research assessment
CoARA Commitment 5 = Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 = Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 = Exchange practices and experiences to enable mutual learning within and beyond the Coalition
CoARA Commitment 9 = Communicate progress made on adherence to the Principles and implementation of the Commitments
CoARA Commitment 10 = Evaluate practices, criteria and tools based on solid evidence and the state-of-the-art in research on research, and make data openly available for evidence gathering and research
User - Funder = User could involve Funders and regional authorities
User - Institutes = User could involve Research institutions
User - Academies = User could involve Academies and learned societies
User - Research Groups = User could involve Research groups
User - Meta-Researchers = User could involve Meta-researchers
User - Scientific editors and publishers = User could involve Scientific editors and publishers
-->

::: {.callout-warning icon=false}

## Objectives and potential outcome
<!--
PROMPTS:
- What happens if this is successful? What changes if this works? 
- What improvements are we aiming for?
- These can be related to the main questions
- If there are multiple experiments fitting, put them here
-->

Objectives of evaluating negative and null results include:

- Increase the openness and reporting of negative and null results  
- Reduce publication bias towards positive results  
- Recognize efforts of researchers beyond just what’s positive/”novel” (and peer reviewers) reduce waste from unnecessary replication  
- Strengthen evidence-based practice (e.g. bad pharma - negative results show dangers and can prevent negative effects) - publication bias  
- Reduce temptation for questionable/non-ethical practices (removal of outliers, changing data) - Enable research integrity  

:::

## Research domains
<!--
PROMPTS:
- Which domain(s) can this experiment be applied in? 
-->

This idea is relevant in a variety of contextx (hiring, promotion, funding, etc.) but is mostly applicable for hypothesis-driven research and empirical research (where n > 1).

## Context and considerations
<!--
PROMPTS:
- Who is carrying out the evaluation? Who is this experiment for? (i.e., Target groups - Funders? Institutions? Individual researchers? Research domains?); 
- What type of assessment does this work on (Team/individual/project/institutional);
- What is the objective of evaluation exercise linked to the type of assessment
- What are the things that change in the experiment?
- Nature of the organization carrying out evaluation exercise; What type of assessment (Team/individual/project/institutional); Objective of evaluation exercise linked to the type of assessment
-->
Investing in the importance of negative results in assessments is a cultural change and it will often require a systemic experiment - not just on the evaluation itself, but on the whole practice of research. As such, a holistic approach may be needed, with everyone working together to induce the change.  

It may be important to define the story/strategy/route behind this (and entry point) - what are the steps (and in what order) to push towards this. It may also be important to consider how this is done in practice, and what is considered in the evaluation. For example, should researchers include all null/negative findings or only the most relevant?   

**Experiments will generally need:**  

- Researchers doing the null work/having the data  
- Platform to publish the results  
- People to evaluate the negative results (and guidance/training on how to evaluate them)  
- Funders to recognize it in pre- and post-project evaluation  

**Targeting the evaluation or recognition of null and negative results in an experiment may take a variety of forms in a variety of contexts. For examples, experimentation may be interested in:**  
  
- Looking at whether the ratio of negative results published to positive results published in a certain context/centre may be used as a metric for creativity or risk taking  
- Looking at the impact of recognition of pre-prints with negative/null results in assessment of researchers or research outputs  
- Looking at the impact of evaluators asking for negative/null results published as an output (i.e., formally recognize these as a part of output)
- Looking at the demands from funders with regards to publication and appreciation of negative results (e.g., In the final reports - accept that only null results may be published and consider this to be satisfactory to provide the last chunk of grant money)
- Looking at the impact of publishing in Open Research repository - Open Research Europe, Wellcome Open Research, pre-print servers (not peer-reviewed), on the outputs reported
- Moving assessments away from novelty and impact in peer-review process of research outputs - peer review tailored towards goals so that not everything needs to aim for novelty
- Looking at the recognition of pre-registration in the evaluation process or implementation of a requirement of pre-registration by the research(ers) once funded (e.g. before contract signature)
- Understanding how negative results reported in “Additional material/negative results” sections in papers/outputs may be used in research assessment  
  

## Challenges and mitigations
<!--
PROMPTS:
- Each challenge and mitigation grouped together
- If there isn’t mitigation, say so
- Tips and tricks for preparing and running the experiment
-->

**Challenge: Culture of prestige** – There is a huge culture of recognition around high-impact factor journals. This may be difficult to go around, especially the importance of those outputs in university rankings which bring a higher level of resistance.  
**Mitigation:** Change the culture at all levels  
**Mitigation:** Get funders and seniors in institutions on board  
  
**Challenge: Acceptance from funders** – Given the role of funders and the importance of 'impact' for research funding (and for obtaining trust and support from society and governments), it may be difficult to ensure that funders are on board with this idea. However, without funders' support, it may be difficult to obtain real buy-in from institutions.  
**Mitigation:** Raise awareness on the crucial role of negative findings in building robust knowledge, and in turn, in the role that this may have in helping to avoid harm (e.g., unpublished side effects and ineffective drugs).  
  
**Challenge: Lack of finalisation of projects that yield negative results** – Risk of abandonment of studies that start showing null results  
**Mitigation:** Ensure protected project time and funding to complete projects regardless or results  
  
**Challenge: Metrics impact** – Risk of not being cited  
**Mitigation:** Using “Additional material/negative results” sections in papers/outputs to make sure negative results are accessible with the publication  
  
**Challenge: Culture** – Not much of a “story” around negative/null results  
**Mitigation:** Again, bring more recognition by funders/institutions to shift culture to value negative results
  
## Evaluating success
<!--
PROMPTS:
- Evaluation criteria for the experiment 
- How do you know it worked or didn’t?
-->

## Related CoARA commitments
<!--
PROMPTS:
Directly reference as many of the 10 CoARA commitments as are fitting
-->

**CoARA Commitment 1** – Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research  
**CoARA Commitment 3** – Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index  
**CoARA Commitment 6** – Review and develop research assessment criteria, tools and processes

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 
<!--
PROMPTS:
- Add templates from funders and institutions if existing
-->

## Case examples and literature
<!--
PROMPTS:
Any organisation names, links, authors that may be relevant to look into
-->

## Other resources
<!--
PROMPTS:
Include any other resource here
-->


# Comments/lived examples
<!--
PROMPTS:
Section to be kept blank, for input within the idea catalogue
-->





