---
title: "Research users impacted as evaluators"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Inclusivity", "Aim: Bias mitigation", "Aim: Recognition", "Aim: Diversity", "Aim: Alternative questions", "CoARA Commitment 1", "CoARA Commitment 2", "CoARA Commitment 6", "Target: Funder", "Target: Scholarly association"]
description: "Individuals or their representatives directly impacted by the research activities can be involved as reviewers, as one specific category of stakeholders."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

- Improve the value of research for users
- Include targeted populations in the decision of resource attribution

:::

## Research domains

## Context and considerations

Depending on the group represented, their role in the research assessment process and their requirements in terms of communication have to be carefully considered in the process design.

## Challenges and mitigations

**Challenge: Jargon from the proposal may limit contributions
Mitigation:** Ensure researchers know the composition of the panel and support them in making efficient communication (RI could be used as a case on this)

**Challenge: Will evaluate impact, but possibly not the quality of the scientific method
Mitigation:** assign different elements of the assessment to different assessors so they feel confident in those elements (but this can create different levels of scoring needed)

## Evaluating success

## Related CoARA commitments

CoARA Commitment 1 - Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 - Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 6 - Review and develop research assessment criteria, tools and processes

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 

## Case examples and literature

Pavee Point – an organisation that advocates for the Traveller and Roma communities in Ireland – has published a **[guide for conducting inclusive and ethical research with Traveller and Roma individuals and communities](https://www.paveepoint.ie/wp-content/uploads/2025/12/Pavee-Approach-to-Inclusive-Research-With-Travellers-and-Roma.pdf)

## Other resources

# Case Studies or Implementation Examples

