---
title: "Recognition of peer Review"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Recognition", "Aim: Inclusivity", "Aim: Bias mitigation", "Aim: Value process", "CoARA Commitment 1", "CoARA Commitment 2", "CoARA Commitment 6", "CoARA Commitment 7", "Target: Editor and publisher", "Target: Academic Institution", "Target: Funder", "Target: Meta-Researcher"]
description: "Recognition of peer review treats reviewing as a measurable scholarly contribution. It enhances transparency and accountability, incentivizes high-quality evaluations, and integrates review activity into research assessment systems—acknowledging its essential role in maintaining research integrity, community service, and the advancement of disciplinary standards."
image: false
---

<!--
GENERAL GUIDELINES:
- Use this guide to style all text: https://quarto.org/docs/authoring/markdown-basics.html
- Tags (apply as relevant):
Level 0 = Level of completeness: 0 – The experiment only contains the description and minimal details. This level is meant to provide inspiration for experiments that can be developed further by those experimenting.
Level 1 = Level of completeness: 1 –  The experiment contains minimal details. Organisations will need to build the experimentation plan before they can implement the idea.
Level 2 = Level of completeness: 2 – The experiment contains minimal details that may help with the design and implementation, but organisations will need to build most of the experimentation plan before they can fully implement the idea.
Level 3 = Level of completeness: 3 – The experiment contains some details that may help with the design and implementation, but organisations will need to finalise the experimentation plan before they can fully implement the idea.
Level 4 = Level of completeness: 4 – The experiment contains details that can provide useful guidance for implementation, but additional research will need to be done by experimenting organisation. Few real life cases exist.
Level 5 = Level of completeness: 5 – The experiment contains sufficient details to be implemented, and it has already been experimented in some organisations providing cases, additional suggestions, and often learned lessons.
Aim: Value process = Create an assessment process based upon what the different players in research value
Aim: Inclusivity = Make research more inclusive and equitable through assessment
Aim: Bias mitigation = Mitigate the negative effects of bias on assessment
Aim: Recognition = Recognize process and culture through assessment
Aim: Diversity = Foster diversity through assessment
Aim: Collaboration = Foster collaboration through assessment
Aim: Alternative questions = Ask assessment questions differently
CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 = Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 3 = Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index
CoARA Commitment 4 = Avoid the use of rankings of research organisations in research assessment
CoARA Commitment 5 = Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 = Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 = Exchange practices and experiences to enable mutual learning within and beyond the Coalition
CoARA Commitment 9 = Communicate progress made on adherence to the Principles and implementation of the Commitments
CoARA Commitment 10 = Evaluate practices, criteria and tools based on solid evidence and the state-of-the-art in research on research, and make data openly available for evidence gathering and research
Target: Funder = Target user could involve funding agencies and regional authorities
Target: Academic Institution = Target user could involve research institutions, higher education institutions, and research performing organisations
Target: Scholarly association = Target user could involve academies, scholarly associations, and learned societies
Target: Research Group = Target user could involve Research groups
Target: Individual scholar = Target user could involve individual scholars, including researchers, research students, or research staff
Target: Meta-Researcher = Target user could involve Meta-researchers
Target: Editor and publisher = Target user could involve scientific editors and publishers
-->

::: {.callout-warning icon=false}

## Objectives and potential outcome
<!--
PROMPTS:
- What happens if this is successful? What changes if this works? 
- What improvements are we aiming for?
- These can be related to the main questions
- If there are multiple experiments fitting, put them here
-->

- Enhance transparency and accountability
- Incentivize high-quality evaluations
- Integrate review activity into research assessment systems
- Acknowledging the essential role of peer review in maintaining research integrity, community service, and the advancement of disciplinary standards

:::

## Research domains
<!--
PROMPTS:
- Which domain(s) can this experiment be applied in? 
-->

Recognition of peer review can target journal peer-review, book review, thesis review, conference abstract review, grant application review, as well as general assessment review (e.g., hiring, tenure, promotion, sholarship, awards, etc).

## Context and considerations
<!--
PROMPTS:
- Who is carrying out the evaluation? Who is this experiment for? (i.e., Target groups - Funders? Institutions? Individual researchers? Research domains?); 
- What type of assessment does this work on (Team/individual/project/institutional);
- What is the objective of evaluation exercise linked to the type of assessment
- What are the things that change in the experiment?
- Nature of the organization carrying out evaluation exercise; What type of assessment (Team/individual/project/institutional); Objective of evaluation exercise linked to the type of assessment
-->


## Challenges and mitigations
<!--
PROMPTS:
- Each challenge and mitigation grouped together
- If there isn’t mitigation, say so
- Tips and tricks for preparing and running the experiment
-->

**Challenge:** if peer review is only acknowledged numerically, there is a risk that it becomes a quantitative metric devoid of meaning.  
**Mitigation:** Finding different ways of making peer review more open (see [related idea](https://eui-library.github.io/coara-idea-catalogue/ideas/fully-open-peerreview/index.html)) would bring more qualitative elements to the peer review recognition, on top of increasing the openness and enabling more learning and research opportunities from the reviews process.

## Evaluating success
<!--
PROMPTS:
- Evaluation criteria for the experiment 
- How do you know it worked or didn’t?
-->


## Related CoARA commitments
<!--
PROMPTS:
Directly reference as many of the 10 CoARA commitments as are fitting
-->

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 
<!--
PROMPTS:
- Add templates from funders and institutions if existing
-->

## Case examples and literature
<!--
PROMPTS:
Any organisation names, links, authors that may be relevant to look into
-->

Several peer reviewed journals now offer peer reviewers the option to have their peer review acknowledged on [ORCID](https://support.orcid.org/hc/en-us/articles/360006971333-Peer-Reviews) or on the [Web of Science Reviewer Recognition Service](https://clarivate.com/academia-government/scientific-and-academic-research/publisher-solutions/web-of-science-reviewer-recognition-service/), formerly Publons. In many cases, publishers also offer discount on Article Publishing Charges for peer reviewers, although this practice is generally thought of as an incentive which in itself does not necessarily generate academic recognition.

See for example the dedicated page from [Wiley](https://authors.wiley.com/Reviewers/journal-reviewers/recognition-for-reviewers/index.html), in which they explain that peer reviewers can also claim Continuing Medical Education (CME) Credits, and that they can receive Reviewer Recognition Certificates. The [BMJ](https://authors.bmj.com/for-reviewers/reviewer-recognition/) has a similar system, adding also a public mention of reviewers' names shared on an *annual list of reviewers* where the BMJ group expresses thanks to peer reviewers for their "contribution to maintaining the quality of research literature". Similar systems are in place at most publishers, with some adding their distinctions. For instance, [IOPscience](https://publishingsupport.iopscience.iop.org/publishing-support/reviewers/recognition-for-reviewers/) also has dedicated ways to recognise peer reviewers through Trusted Reviewer status and Outstanding Reviewer Awards, on top of ensuring that peer reviews are acknowledges on the Web of Science Reviewer Recognition Service.

Funders are also starting to recognise peer review, for example, [UKRI now offers peer reviewer recognition through ORCID](https://je-s.rcuk.ac.uk/Handbook/index.htm#t=pages%2FUpdatingAccountPersonalandExpe%2FORCID_Peer_Review_Credit.htm).

## Other resources
<!--
PROMPTS:
Include any other resource here
-->


# Comments/lived examples
<!--
PROMPTS:
Section to be kept blank, for input within the idea catalogue
-->



