---
title: "Team Tenure"
author: "Experiments in Assessment WG"
date: last-modified
categories: [Level 1, Challenge - Process, Challenge - Inclusivity, Challenge - Process Culture, Challenge - Diversity, Challenge - Collaboration, Challenge - Different Questions, CoARA Commitment 1, CoARA Commitment 6, User - Institutes, User - Research Groups, User - Meta-Researchers]
description: "Team tenure is a way to provide stability of funding (i.e., through tenure as a permanent funding streams) for a research group rather than for individual researchers, enabling a broader division of tasks and skills specialisation within the group. This idea is linked to the concept of Team Assessment."
image: false
---

<!--
GENERAL GUIDELINES:
- Use this guide to style all text: https://quarto.org/docs/authoring/markdown-basics.html
- Tags (apply as relevant):
Level 0 = Level of completeness: 0 – The experiment only contains the description and minimal details. This level is meant to provide inspiration for experiments that can be developed further by those experimenting.
Level 1 = Level of completeness: 1 –  The experiment contains minimal details. Organisations will need to build the experimentation plan before they can implement the idea.
Level 2 = Level of completeness: 2 – The experiment contains minimal details that may help with the design and implementation, but organisations will need to build most of the experimentation plan before they can fully implement the idea.
Level 3 = Level of completeness: 3 – The experiment contains some details that may help with the design and implementation, but organisations will need to finalise the experimentation plan before they can fully implement the idea.
Level 4 = Level of completeness: 4 – The experiment contains details that can provide useful guidance for implementation, but additional research will need to be done by experimenting organisation. Few real life cases exist. 
Level 5 = Level of completeness: 5 – The experiment contains sufficient details to be implemented, and it has already been experimented in some organisations providing cases, additional suggestions, and often learned lessons. 
Challenge - Process = Create an assessment process based upon what the different players in research value
Challenge - Inclusivity = Make research more inclusive and equitable through assessment
Challenge - Bias Mitigation = Mitigate the negative effects of bias on assessment
Challenge - Process Culture = Recognize process and culture through assessment
Challenge - Diversity = Foster diversity through assessment
Challenge - Collaboration = Foster collaboration through assessment
Challenge - Different Questions = Ask assessment questions differently
CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 = Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 3 = Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index
CoARA Commitment 4 = Avoid the use of rankings of research organisations in research assessment
CoARA Commitment 5 = Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 = Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 = Exchange practices and experiences to enable mutual learning within and beyond the Coalition
CoARA Commitment 9 = Communicate progress made on adherence to the Principles and implementation of the Commitments
CoARA Commitment 10 = Evaluate practices, criteria and tools based on solid evidence and the state-of-the-art in research on research, and make data openly available for evidence gathering and research
User - Funder = User could involve Funders and regional authorities
User - Institutes = User could involve Research institutions
User - Academies = User could involve Academies and learned societies
User - Research Groups = User could involve Research groups
User - Meta-Researchers = User could involve Meta-researchers
User - Scientific editors and publishers = User could involve Scientific editors and publishers
-->

::: {.callout-warning icon=false}

## Objectives and potential outcome
<!--
PROMPTS:
- What happens if this is successful? What changes if this works? 
- What improvements are we aiming for?
- These can be related to the main questions
- If there are multiple experiments fitting, put them here
-->

Objectives include:
- Providing stability of funding for a research group rather than for individual researchers, enabling a broader division of tasks and skills specialisation within the group (i.e., not everyone needs to find funding and publish research articles, but everyone is essential to the functioning of the group).  
- Contributes to diversity - allowing people to focus on their expertise/strengths/preferences  
- Help provide visibility/benefit for groups/domains that are generally underrepresented - potentially even fostering collaboration/interdisciplinarity between domains

:::

## Research domains
<!--
PROMPTS:
- Which domain(s) can this experiment be applied in? 
-->

This experiment applies to research and education institutions where researchers need to submit an application to obtain permanency (i.e., Tenure).  

## Context and considerations
<!--
PROMPTS:
- Who is carrying out the evaluation? Who is this experiment for? (i.e., Target groups - Funders? Institutions? Individual researchers? Research domains?); 
- What type of assessment does this work on (Team/individual/project/institutional);
- What is the objective of evaluation exercise linked to the type of assessment
- What are the things that change in the experiment?
- Nature of the organization carrying out evaluation exercise; What type of assessment (Team/individual/project/institutional); Objective of evaluation exercise linked to the type of assessment
-->

For Team Tenure to work, a few elements may need to be considered:
- Broad topic is chosen based on strategic needs of the institution
- Need to create a group of job descriptions that cover the needs of such a group, to specify the personnel needs of that topic
- The group would obtain permanency, but a decision needs to be made on whether individuals also obtain permanent positions as a result
- It may be necessary to build a team covering the strategic needs and goals of the team, and enabling a stable group structure as opposed to an individual
- Structure should be built based on the needs of the institution

* **Must fit strategic needs of the institution - following normal tenure committee procedure**
  + Maybe need different guidelines/procedures than traditional tenure (also for runtime of ongoing tenured group)

* **Who is the right person/group to say who the right people are for the team?**  
  + Strategic/central evaluation vs. letting the group leader pick their team**
  + Aims to find a leader with a co-interest with the institution to have a stable team (vs. a high-turnover group of ECRs focusing on productivity) - different leadership

* **Like funding scheme for team - define the composition of the team in the proposal itself** (e.g. potential job ads - how do you find the right profiles to fit in the team)
  + E.g. 1 lead profile + 2 other profiles fitting the needs of the project - more of a separate hiring process
  + After first period of funding is over, can apply for successive phase - have to show why they fit together, and why the team works as it does  
  
* **Think about the profiles that are needed to cover the group’s goals**
  
* **Topic should be broad, and not too specific**  
  + Should be also more thought-through than a typical grant/group
  + E.g. creating a mini-interdisciplinary center - fostering collaboration between domains
  
* **Important to think about the model of tenure that the institution wants**
  + Is this temporary/permanent for the people inside?
  + How will the team look?
  + Is there evaluation during/after?
  + Is there an ending of the group? If so, where do we want them to land?

* **PI needs to be a better leader in such a group - longer term perspective for the people**
  + Need to take care of your team better
  + Damage done is worse compared to a “short-term” project


## Challenges and mitigations
<!--
PROMPTS:
- Each challenge and mitigation grouped together
- If there isn’t mitigation, say so
- Tips and tricks for preparing and running the experiment
-->

**Several questions and challenges may result from implementing Team Tenure. The few questions below may help stimulate a discussion on these challenges and in building strategies to mitigate them in your context.**  
  
* **Everyone wants to be a leader.**
  + Note: It it possible that this is mitigated in the long run, the advantages of being a recognised team member with security reduce the unequal advantage of being in a leadership position, reducing the general desire for a leadership role. 

* **People don’t think in terms of the team, rather think about the people they already have/want**
  + Need to have blue sky thinking first?
  + When the job description fits the project/group, it’s generally more creative/broader - not a checklist of a person who is already there

* **Needs of the topic can change, topic can also become irrelevant/shift drastically**
  + If the topic is broad, there might be ways to pivot/shift

* **Can you run an effective team with only tenured people? How do you manage/create fresh idea generation/innovativeness**
  + In the tenure, require things that boost this - e.g. cross-sectoral/domain mobility
  + Make sure they are constantly challenged/exposed to new or different things

* **What if a person drops out of the group? Who’s the backup?**
  + Job descriptions for each role should be prepared at the beginning, can be updated as the group moves forward

* **How do we develop people who aren’t leaders but want to do different roles?**
  + Career development “go beyond your bubble”

* **How do we encourage/fairly incentivize people who want to remain in a non-leadership role?**
  + Develop career tracks for different roles 

* **Need very strong leaders in these groups - not just scientifically focused, more able to lead their team well - different type of person**
  + Hiring of a PI needs to be mainly based on leadership more than research outputs
  + Continuous and recurrent training, reflective leadership, etc. to maintain this

* **If no end to the group, and the topic is super broad, you create a new “research institute”/unit in your environment**
  + If you start with a long-term but still temporary thing, then the topic/team has developed away from the initial idea. Need to be reflective on the purpose/goals of the group

* **If the team is successful, need to ask “why is this not a typical group that has always existed”**


## Evaluating success
<!--
PROMPTS:
- Evaluation criteria for the experiment 
- How do you know it worked or didn’t?
-->
**The following achievements may help determine whether the experiment can be considered a success.**

- Engrained as a team in their focus areas - have a set of projects/funding chains in place, activities in internationalization/teaching/etc. 
- For the institution/group - achieving more as a group than as if the group wasn’t there or project based funding or something more traditional
- Career development for people in the “more junior” positions 
- Stability for people in traditionally non-tenure position, for those that don’t want to be a PI
- If the team is successful and looks like a traditional research group/institute (with funding/success measures/etc.) - what do you do with this

## Related CoARA commitments
<!--
PROMPTS:
Directly reference as many of the 10 CoARA commitments as are fitting
-->

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea (if available).

## Templates from funders and institutions 
<!--
PROMPTS:
- Add templates from funders and institutions if existing
-->

## Case examples and literature
<!--
PROMPTS:
Any organisation names, links, authors that may be relevant to look into
-->

## Other resources
<!--
PROMPTS:
Include any other resource here
-->


# Comments/lived examples
<!--
PROMPTS:
Section to be kept blank, for input within the idea catalogue
-->


