---
title: "Fostering co-creation of research programmes"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 1", "Aim: Inclusivity", "Aim: Diversity", "Aim: Collaboration", "Aim: Alternative questions", "Aim: Value process", 
"CoARA Commitment 1", "CoARA Commitment 2", "CoARA Commitment 6", "CoARA Commitment 8", "Target: Funder", "Target: Academic Institution", "Target: Scholarly association", "Target: Research Group"]
description: "Engage with community while designing funding programmes to ensure the programmes designed are as diverse and includsive as possible and are relevant and speaking to the challenges faced by underserved communities."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

Engaging with community while designing funding programmes may help ensure the programmes designed are as diverse and includsive as possible and are relevant and speaking to the challenges faced by underserved communities. (e.g., case: RI racism reserach)

:::

## Research domains

## Context and considerations

This may include:  
- Engagement of community stakeholders in co-designing calls
- Making sure researchers from the community are engaged in building the call (from funded and nun-funded applicants)
- Involving communities in setting evaluation criteria for the call with the goal of making sure evaluation criteria are fit for purpose

## Challenges and mitigations

## Evaluating success

## Related CoARA commitments

# Relevant resources and literature 

## Templates from funders and institutions 

## Case examples and literature

## Other resources
The [PPI Ignite Network](https://ppinetwork.ie) which aims to promote excellence and inspires innovation in public and patient involvement in health and social care research is an Irish initiative that may help support PPI activities. Touching base with such a group could be helpful if an organisation wishes to put together a co-created funding programmes. 

# Comments/lived examples

