---
title: "Evaluation of EDI action plan"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Value process", "Aim: Inclusivity", "Aim: Diversity", "Aim: Recognition", "Target: Funder", "Target: Academic institution", "CoARA Commitment 1", "CoARA Commitment 6"]
description: "In this idea, an EDI action plan must be submitted with an application, and this action plan is then evaluated as part of the process. This aims to ensure that EDI aspects are an integral part of what is supported in research."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

- Give EDI an explicit space in grant funding
- Ensure that EDI aspects are an integral part of what is supported in research.

:::

## Research domains

## Context and considerations

## Challenges and mitigations

## Evaluating success

## Related CoARA commitments

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 

The New Frontiers in Research Fund from the Canadian Social Sciences and Humanities Research Council includes EDI as part of its assessment, encouraging applicants to write an EDI plan and asking them to address 'EDI in research practice' within their application. [https://sshrc-crsh.canada.ca/funding-financement/nfrf-fnfr/edi-eng.aspx](https://sshrc-crsh.canada.ca/funding-financement/nfrf-fnfr/edi-eng.aspx)

## Case examples and literature

## Other resources

# Comments/lived examples

