---
title: "Mentee evaluation"
author: "Experiments in Assessment WG"
date: "2025-03-03"
categories: [Level 1, CoARA Commitment 1, CoARA Commitment 2, CoARA Commitment 6, User - Institutes, User - Academies, User - Research Groups, User - Meta-Researchers]
description: "Evaluating mentorship and making mentorship a part of the assessment. This is especially relevant for PIs, and aims to look at the mentorship and culture created with the applicants."
image: false
---

<!--
GENERAL GUIDELINES:
- Use this guide to style all text: https://quarto.org/docs/authoring/markdown-basics.html
- Tags (apply as relevant):
Level 0 = Level of completeness: 0 – The experiment only contains the description and minimal details. This level is meant to provide inspiration for experiments that can be developed further by those experimenting.
Level 1 = Level of completeness: 1 –  The experiment contains minimal details. Organisations will need to build the experimentation plan before they can implement the idea.
Level 2 = Level of completeness: 2 – The experiment contains minimal details that may help with the design and implementation, but organisations will need to build most of the experimentation plan before they can fully implement the idea.
Level 3 = Level of completeness: 3 – The experiment contains some details that may help with the design and implementation, but organisations will need to finalise the experimentation plan before they can fully implement the idea.
Level 4 = Level of completeness: 4 – The experiment contains details that can provide useful guidance for implementation, but additional research will need to be done by experimenting organisation. Few real life cases exist. 
Level 5 = Level of completeness: 5 – The experiment contains sufficient details to be implemented, and it has already been experimented in some organisations providing cases, additional suggestions, and often learned lessons. 
Challenge - Process = Create an assessment process based upon what the different players in research value
Challenge - Inclusivity = Make research more inclusive and equitable through assessment
Challenge - Bias Mitigation = Mitigate the negative effects of bias on assessment
Challenge - Process Culture = Recognize process and culture through assessment
Challenge - Diversity = Foster diversity through assessment
Challenge - Collaboration = Foster collaboration through assessment
Challenge - Different Questions = Ask assessment questions differently
CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 = Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 3 = Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index
CoARA Commitment 4 = Avoid the use of rankings of research organisations in research assessment
CoARA Commitment 5 = Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 = Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 = Exchange practices and experiences to enable mutual learning within and beyond the Coalition
CoARA Commitment 9 = Communicate progress made on adherence to the Principles and implementation of the Commitments
CoARA Commitment 10 = Evaluate practices, criteria and tools based on solid evidence and the state-of-the-art in research on research, and make data openly available for evidence gathering and research
User - Funder = User could involve Funders and regional authorities
User - Institutes = User could involve Research institutions
User - Academies = User could involve Academies and learned societies
User - Research Groups = User could involve Research groups
User - Meta-Researchers = User could involve Meta-researchers
User - Scientific editors and publishers = User could involve Scientific editors and publishers
-->

::: {.callout-warning icon=false}

## Objectives and potential outcome
<!--
PROMPTS:
- What happens if this is successful? What changes if this works? 
- What improvements are we aiming for?
- These can be related to the main questions
- If there are multiple experiments fitting, put them here
-->

Embedding mentee evaluation in assessment may lead to:

- Evaluative and supportive impact on leaders in academia
- Increase leadership competences and skills - e.g. better leaders in research
- Better transparency in leadership expectations - knowing what is needed to become a leader/manager
- Make it easier for people to transition into leadership positions - helping people in the transition
- More diversity in academic leadership (e.g. 1st generation researchers, gender diversity, etc.)

:::

## Research domains
<!--
PROMPTS:
- Which domain(s) can this experiment be applied in? 
-->

This idea can lend itself to any context where it can be targeted towards leaders. It is expected that this is especially applicable to research institutions, but it could also apply to funders in relation to grants that support leadership and group management. 

## Context and considerations
<!--
PROMPTS:
- Who is carrying out the evaluation? Who is this experiment for? (i.e., Target groups - Funders? Institutions? Individual researchers? Research domains?); 
- What type of assessment does this work on (Team/individual/project/institutional);
- What is the objective of evaluation exercise linked to the type of assessment
- What are the things that change in the experiment?
- Nature of the organization carrying out evaluation exercise; What type of assessment (Team/individual/project/institutional); Objective of evaluation exercise linked to the type of assessment
-->

Experiments on mentee evaluation can take different forms and target numerous elements of the leadership cycle, including:

- Mentee evaluations for hiring, promotion, and tenure assessment
- Top down evaluation on leadership
- 360 degree evaluations for leaders (i.e., where evaluation takes input from individuals in supervising, equal, and supervised roles - above, middle, below)
- Training/coaching for leaders as parts of grants/institutional positions/etc. 
- Competence/skills frameworks and evaluations in grants/hiring/promotion
- Funds in grants/team budgets for leadership training and development

## Challenges and mitigations
<!--
PROMPTS:
- Each challenge and mitigation grouped together
- If there isn’t mitigation, say so
- Tips and tricks for preparing and running the experiment
-->

Several challenges may impact this idea:

**Challenge: Resistance from leaders** – Research leaders think they are already great leaders, and this isn’t relevant.   
**Mitigation:** Make it mandatory for new leaders  
  
**Challenge: Creating evaluations for all staff (even if it doesn’t exist)**  
**Mitigation:** Embrace a reduced frequency of assessment (See related [idea](https://eui-library.github.io/coara-idea-catalogue/ideas/reducing-frequency-of-assessment/index.html))

**Challenge: Mitigation:** Monitoring improvement and how effective this is  
**Mitigation:** Increased importance of HR staff - bring them into the process  
  
**Challenge: Selection bias** – Mentors select people they know will be positive  
**Mitigation:** Make the template clear enough to allow to 'read between the lines'  
**Mitigation:** Assessor training (i.e., Qualitative evaluation in Pep-CV could be relevant to this, but not open in itself)  
  

## Evaluating success
<!--
PROMPTS:
- Evaluation criteria for the experiment 
- How do you know it worked or didn’t?
-->

Employment satisfaction surveys will show improvement
Reduction in people leaving teams/research groups due to poor leadership
Leaders feel more comfortable in the role
Evaluations will have more leadership components to them when applicable (e.g. hiring leaders, promotion to leadership, grants around leading groups)

## Related CoARA commitments
<!--
PROMPTS:
Directly reference as many of the 10 CoARA commitments as are fitting
-->

**CoARA Commitment 1** – Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research  
**CoARA Commitment 2** – Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators  
**CoARA Commitment 6** – Review and develop research assessment criteria, tools and processes  

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

Vitae Reseacher Development Framework - competence framework for researchers
Competence frameworks for research managers - (https://research-and-innovation.ec.europa.eu/jobs-research/rm-comp-european-competence-framework-research-managers_en#other-eu-competence-frameworks)[https://research-and-innovation.ec.europa.eu/jobs-research/rm-comp-european-competence-framework-research-managers_en#other-eu-competence-frameworks]


## Templates from funders and institutions 
<!--
PROMPTS:
- Add templates from funders and institutions if existing
-->

## Case examples and literature
<!--
PROMPTS:
Any organisation names, links, authors that may be relevant to look into
-->

FNR Mentee evaluation provides gender balanced list of former mentees, FNR decides on two, sends them an evaluation template to them - (https://www.researchluxembourg.org/en/research-landscape/research-culture/mentorship-charter/)[https://www.researchluxembourg.org/en/research-landscape/research-culture/mentorship-charter/]


## Other resources
<!--
PROMPTS:
Include any other resource here
-->


# Comments/lived examples
<!--
PROMPTS:
Section to be kept blank, for input within the idea catalogue
-->









