---
title: "Fully open peer-review"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 1", "Aim: Value process", "Aim: Inclusivity", "Aim: Bias mitigation", "Aim: Recognition", "Aim: Diversity", "Aim: Collaboration", "CoARA Commitment 1", "CoARA Commitment 2", "CoARA Commitment 6", "CoARA Commitment 7", "Target: Editor and publisher", "Target: Academic Institution", "Target: Funder", "Target: Research Group", "Target: Meta-Researcher"]
description: "Peer review in which reviewers and applicants know each other's identities. This can extend to public sharing of peer review reports."
image: false
---

<!--
GENERAL GUIDELINES:
- Use this guide to style all text: https://quarto.org/docs/authoring/markdown-basics.html
- Tags (apply as relevant):
Level 0 = Level of completeness: 0 – The experiment only contains the description and minimal details. This level is meant to provide inspiration for experiments that can be developed further by those experimenting.
Level 1 = Level of completeness: 1 –  The experiment contains minimal details. Organisations will need to build the experimentation plan before they can implement the idea.
Level 2 = Level of completeness: 2 – The experiment contains minimal details that may help with the design and implementation, but organisations will need to build most of the experimentation plan before they can fully implement the idea.
Level 3 = Level of completeness: 3 – The experiment contains some details that may help with the design and implementation, but organisations will need to finalise the experimentation plan before they can fully implement the idea.
Level 4 = Level of completeness: 4 – The experiment contains details that can provide useful guidance for implementation, but additional research will need to be done by experimenting organisation. Few real life cases exist.
Level 5 = Level of completeness: 5 – The experiment contains sufficient details to be implemented, and it has already been experimented in some organisations providing cases, additional suggestions, and often learned lessons.
Aim: Value process = Create an assessment process based upon what the different players in research value
Aim: Inclusivity = Make research more inclusive and equitable through assessment
Aim: Bias mitigation = Mitigate the negative effects of bias on assessment
Aim: Recognition = Recognize process and culture through assessment
Aim: Diversity = Foster diversity through assessment
Aim: Collaboration = Foster collaboration through assessment
Aim: Alternative questions = Ask assessment questions differently
CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 = Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 3 = Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index
CoARA Commitment 4 = Avoid the use of rankings of research organisations in research assessment
CoARA Commitment 5 = Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 = Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 = Exchange practices and experiences to enable mutual learning within and beyond the Coalition
CoARA Commitment 9 = Communicate progress made on adherence to the Principles and implementation of the Commitments
CoARA Commitment 10 = Evaluate practices, criteria and tools based on solid evidence and the state-of-the-art in research on research, and make data openly available for evidence gathering and research
Target: Funder = Target user could involve funding agencies and regional authorities
Target: Academic Institution = Target user could involve research institutions, higher education institutions, and research performing organisations
Target: Scholarly association = Target user could involve academies, scholarly associations, and learned societies
Target: Research Group = Target user could involve Research groups
Target: Individual scholar = Target user could involve individual scholars, including researchers, research students, or research staff
Target: Meta-Researcher = Target user could involve Meta-researchers
Target: Editor and publisher = Target user could involve scientific editors and publishers
-->

::: {.callout-warning icon=false}

## Objectives and potential outcome
<!--
PROMPTS:
- What happens if this is successful? What changes if this works? 
- What improvements are we aiming for?
- These can be related to the main questions
- If there are multiple experiments fitting, put them here
-->

Some objectives and potential outcomes include:
- Peer review can be recognised and rewarded
- Greater responsibility of peer reviewers and accountability for the quality of their review
- Opportunity to make peer review an educational experience (if reviews are shared publicly)
- Possibility to monitor and ensure the openness of the diversity of reviewer pools
- Possibility to reduce language biases by enabling applicants to explain unclear elements of their proposals
- Potentially reduces number of appeals
- Reduced competition in the research environment

:::

## Research domains
<!--
PROMPTS:
- Which domain(s) can this experiment be applied in? 
-->

Open peer review has been increasingly used by scientific journals. Several journals now provide reviewers' identities and/or publish their full review. While this approach is increasingly common in scientific publishing, it is not yet common practice in research funding application nor in hiring, tenure and promotion assessments. 

## Context and considerations
<!--
PROMPTS:
- Who is carrying out the evaluation? Who is this experiment for? (i.e., Target groups - Funders? Institutions? Individual researchers? Research domains?); 
- What type of assessment does this work on (Team/individual/project/institutional);
- What is the objective of evaluation exercise linked to the type of assessment
- What are the things that change in the experiment?
- Nature of the organization carrying out evaluation exercise; What type of assessment (Team/individual/project/institutional); Objective of evaluation exercise linked to the type of assessment
-->
Open peer review can refer to different models that aim to bring greated transparency to the review process. In some cases, the identity of reviewers is disclosed to applicants and/or published publicly. In other cases, the review reports are completely open, shared with applicants or made open publicly, this can be done with or without the reviewers' identities being disclosed. 

Several opinions and studies have been made on the impacts that such openness may have on the peer review process. In some cases, it is believed that openness prevents "reviewers ‘hiding behind’ anonymity when criticizing the work of others", but other works suggest that "reviewers may shy away from being critical in this context". Gutrie, S. 2019 ['Innovating in the Research Funding Process: Peer Review Alternatives and Adaptations'](https://academyhealth.org/publications/2019-11/innovating-research-funding-process-peer-review-alternatives-and-adaptations)) provides a useful summary of elements to be considered in open peer review, including a list of pros and cons.

UK Research and Innovation (UKRI)'s [Review of Peer Review](https://www.ukri.org/publications/review-of-peer-review/review-of-peer-review-june-2023/) suggests that open peer review "are expected to lead to increased accountability, challenging unjust reviews, giving applicants more voice in the process and increasing overall review quality." They also conclude that since an open peer review system may enable applicants to clarify misunderstandings and some of the application’s content, they may help reduce biases where English (or the local language) is not the applicant's first language.

## Challenges and mitigations
<!--
PROMPTS:
- Each challenge and mitigation grouped together
- If there isn’t mitigation, say so
- Tips and tricks for preparing and running the experiment
-->

**Challenge:** One challenge from open peer review is that it can reduce the honesty of reviewers who have concerns - make reviewers avoid raising issues, especially if the application is from someone renowned in their expertise.  
**Mitigation:** A review process that contains more detailed questions may circumvent this problem, encouraging reviewers to be as honest as possible on more specific and direct questions, thereby transposing the personal responsibility to the review process. 

## Evaluating success
<!--
PROMPTS:
- Evaluation criteria for the experiment 
- How do you know it worked or didn’t?
-->


## Related CoARA commitments
<!--
PROMPTS:
Directly reference as many of the 10 CoARA commitments as are fitting
-->

# Relevant resources and literature 


## Templates from funders and institutions 
<!--
PROMPTS:
- Add templates from funders and institutions if existing
-->

## Case examples and literature
<!--
PROMPTS:
Any organisation names, links, authors that may be relevant to look into
-->

The [Dutch Research Council (NWO)](https://www.nwo.nl/en/apply-funding-how-does-it-work) allows applicants to see reviewer responses and offer a response as part of the application process. In their own words, "As soon as NWO has received the referee reports, we will forward them to you. You will subsequently be given several business days to respond in writing (the ‘rebuttal’). You can answer referees’ questions and address any criticisms in your rebuttal.".

UKRI also allows ten working days for applicants to write a rebuttal (see [here](https://www.ukri.org/publications/review-of-peer-review/review-of-peer-review-june-2023/)).

Examples of fully open Peer Review exist among scientific journals, for instance [eLife](https://elife-rp.msubmit.net/cgi-bin/main.plex?form_type=display_rev_instructions#process) or [F1000 Research](https://f1000research.com/about).

## Other resources
<!--
PROMPTS:
Include any other resource here
-->

Ross-Hellauer, T. (2017) What is open peer review? A systematic review *F1000Research* 6:588. [https://doi.org/10.12688/f1000research.11369.2](https://doi.org/10.12688/f1000research.11369.2)

Liu, Y., Li, S. & Rousseau, R. (2026). Peer review for funding decisions. *Journal of Data and Information Science*, 11(1). [https://doi.org/10.2478/jdis-2025-0050](https://doi.org/10.2478/jdis-2025-0050)

Gutrie, S. 2019 ['Innovating in the Research Funding Process: Peer Review Alternatives and Adaptations'](https://academyhealth.org/publications/2019-11/innovating-research-funding-process-peer-review-alternatives-and-adaptations)

UKRI (2023). Review of peer review. [https://www.ukri.org/publications/review-of-peer-review/review-of-peer-review-june-2023/](https://www.ukri.org/publications/review-of-peer-review/review-of-peer-review-june-2023/)

# Comments/lived examples
<!--
PROMPTS:
Section to be kept blank, for input within the idea catalogue
-->




