---
title: "Wild card for evaluators in the panel"
author: "Experiments in Assessment WG"
date: "2025-02-18"
categories: [Broaden recognition, Diversifying recognition, Funding inclusiveness, Competitive evaluation of people or projects, Funders, Research performing organisations]
description: "TO BE ADDED"
---

::: {.callout-warning icon=false}

## Objectives

- Increase potential high-risk high-reward proposals 
- Getting around potential disciplinary limitations competences/knowledge of reviewer
- Decreasing unconscious and conscious bias, especially with individuals dominating evaluation processes

:::

## Introduction

ABSTRACT - LATER

### Related CoARA commitments


2. Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
6. Review and develop assessment criteria, tools, and processes


## Research domains

This idea applies to all research domains.

## What are potential variables  

- Type of research that gets funded
- Individual criteria for funding recommendation 

## Implementation suggestions 
<!--COMMENT: Also include costs here*-->

- Conflict of interest reporting and check of evaluators is crucial
- Training of evaluators to make sure that the power is used responsibility 
- Personal 

## Potential for the experiment

Enable niche ideas or small topics to be recognised
Reduce discussion time in panels

## Challenges and mitigations



### Challenges

- What about issues regarding what is picked? The proposal is against guidelines/best practices, has conflicts?
- Resistance of scientific community, especially for the proposal knocked out of funding due to this
- 

### Mitigation strategies

- 


## Evaluating success

- Diversity of the evaluator pool (geographic, gender, new vs old partners, etc.)
- Self-assessment feedback from applicants (including off-target effects - does this create a real benefit for the applicants?)
- 


# Relevant resources/literature 
## Templates from funders and institutions 
- **TITLE HERE** - UK - [URL here](link)
- 


## Case examples and literature
- Villum Experiment: A Grant Scheme with Double-blind Evaluation | AFIRE Funders’ Forum - https://www.youtube.com/watch?v=EBSjqWfPBlE 
- 



## Other resources
**PEP-CV**: The Peer Exchange Platform for Narrative-style CVs (PEP-CV) is a resource for the research and innovation community developed by a partnership between funding agencies and researchers. https://pep-cv.mariecuriealumni.eu


# Comments/lived examples 
***TBD***
