---
title: "Qualitative assessor training"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Value process", "Aim: Bias mitigation", "Aim: Diversity", "Aim: Alternative questions", "CoARA Commitment 2", "CoARA Commitment 5", "CoARA Commitment 6", "CoARA Commitment 7", "CoARA Commitment 8", "Target: Funder", "Target: Academic Institution", "Target: Editor and publisher"]
description: "Providing dedicated training to support assessors in reviewing and assessing qualitative information."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

- Build understanding and capacity among reviewers
- Make assessors confident in assessing qualitative information 

:::

## Research domains

This is applicable to any domain where assessors are asked to assess and compare qualitative information, notably relevant in the case of narrative CV assessment (see [associated idea](https://eui-library.github.io/coara-idea-catalogue/ideas/narrative-cvs/index.html)), but it can be relevant to individual and project assessment alike.

## Context and considerations

Experiments in building and providing training for assessors could look at effectiveness of the training in making mor reliable qualitative assessment (as recommended in [this review](https://f1000research.com/articles/14-1345)). This could investigate assessor confidence in assessing qualitative information, repeated scoring consistency, or any other elements that may impact evaluation reliability after the training has been followed.

While training can be provided by the organisation conducting the assessment, funders also report that allowing assessors to interact with one another (exchange) is useful and valuable in improving the assessment. Exchange discussions could be organised before and during assessment exercises. Assessor-to-assessor (peer-to-peer) training can also help. The peer-to-peer platform PEP-CV could be relevant to look into. [https://pep-cv.mariecuriealumni.eu](https://pep-cv.mariecuriealumni.eu)  

## Challenges and mitigations

**Challenge:** Uptake of training may be unequal across assessors.  
**Mitigation:** Making training mandatory for assessors, or providing direct exchange and discussion can motivate assessors to undertake the required training.

## Evaluating success

## Related CoARA commitments

CoARA Commitment 2 - Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 5 - Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 - Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 - Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 - Exchange practices and experiences to enable mutual learning within and beyond the Coalition

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 

## Case examples and literature

FNR Luxembourg provides resources to support assessors in the assessment of narrative CVs (see [https://www.fnr.lu/new-video-resource-for-funders/](https://www.fnr.lu/new-video-resource-for-funders/) and associated [video](https://www.youtube.com/watch?v=q_NCE80xi_w)).

The Royal Society resources on [unconscious bias](https://royalsociety.org/news-resources/publications/2015/unconscious-bias/) may also help support assessors in understanding how they can minimise bias in qualitative assessment.

## Other resources

# Comments/lived examples
