---
title: "Narrative CV"
author: "Experiments in Assessment WG"
date: "2025-03-03"
categories: [Broaden recognition, Diversifying recognition, Funding inclusiveness, Competitive evaluation of people or projects, Funders, Research performing organisations]
description: "This experimental idea aims to change the template for CVs submitted with applications from an itemised format to a structured narrative style. Narrative CVs enable applicants to go beyond closed categories and to express outputs, impacts, activities and skills that would normally be difficult to place in a CV format. Narrative CVs can be implemented for individuals or for teams."
image: false
---
::: {.callout-warning icon=false}

## Objectives

- Increase what is recognized/used in assessment 
- Allow space for diverse career paths, outputs, competences, and achievements
- [NOTE: be more concrete]

:::

## Introduction

This experimental idea aims to change the template for CVs submitted with applications from an itemised format to a structured narrative style. Narrative CVs enable applicants to go beyond closed categories and to express outputs, impacts, activities and skills that would normally be difficult to place in a CV format. Narrative CVs can be implemented for individuals or for teams. 

### Related CoARA commitments

1. Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
2. Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
3. Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index

## Research domains

This idea applies to all research domains.

## What are potential variables  

- Documentation of research 
- Information gathered from applicants 
- Weight of output types on evaluation criteria 
- Language skills impact on evaluation

## Implementation suggestions 

- Look at examples of templates and choose/adapt to your context 
- Training and webinars  
- Use PEP-CV
- Align evaluation criteria 
- Consider guidance for how it’s evaluated
- Consider time spent on evaluation and writing of CVs and training 
- Culture shift 
- Give money to PEP-CV! (mandatory) 


## Challenges and mitigations

### Challenges

- Internal alignment at the institution/change management 
- Disciplinary buy-in 
- Perceived loss of “objectivity” 
- Labor – perception of more difficult/longer to evaluate/complete? 
- Scalability of the process 

### Mitigation discussion 

- FNR has all the answers 
- Consider reducing burden in other aspects of the process 
- Give people more time to review things 
- Consider the format of the CV aligned with your goals/challenges 


## Impact assessment

- Comparing (diverse variables from) selected projects/people 
- Diversity in career progression 



# Relevant resources/literature 
## Templates from funders and institutions 
- **Royal Society, Résumé for Researchers** - UK - [https://royalsociety.org/news-resources/projects/research-culture/tools-for-support/resume-for-researchers/](link)
- **National Institutes of Health, Biosketch** - USA - [https://grants.nih.gov/grants-process/write-application/forms-directory/biosketch](link)
- **UK Research and Innovation, R4RI** - UK - [https://www.ukri.org/publications/resume-for-research-and-innovation-r4ri-template/](link)
- **Ministry of Business, Innovation and Employment (MBIE), Narrative CV** - New Zealand - Multiple templates available from [https://www.mbie.govt.nz/search/SearchForm?Search=narrative%20cv&type[doc]=doc](link)


## Case examples and literature studying narrative CVs
- [https://www.fnr.lu/narrative-cv/](https://www.fnr.lu/narrative-cv/) 
- [https://doi.org/10.1101/2022.03.16.484596](https://doi.org/10.1101/2022.03.16.484596) - SNSF format manuscript


***Note: I just added a few extracted refs, but I have not cleaned up now read through these. Should we consider an order, a short description of why they matter? Should we only use DOIs to be in line with DORA no-journals-mentioned ideas?***

- Aubert Bonn, N., & Bouter, L. (2023). Research Assessments Should Recognize Responsible Research Practices. Narrative Review of a Lively Debate and Promising Developments. In *Handbook of Bioethical Decisions. Volume II* (pub.1160203127; pp. 441–472). [https://doi.org/10.1007/978-3-031-29455-6_27](https://doi.org/10.1007/978-3-031-29455-6_27)
- Aubert Bonn, N., Morris, J. P., Sapcariu, S., & Stroobants, K. (2024). Are Narrative CVs contributing towards shifting research culture? Workshop Report from the 2023 Recognition and Rewards Festival. *F1000Research, 13,* 332. [https://doi.org/10.12688/f1000research.146108.1](https://doi.org/10.12688/f1000research.146108.1)
- Auger, V., & Claes, N. (2023). Comment on "Responsible Research Assessment: Implementing DORA for hiring and promotion in psychology”. *PsyArXiv.* [https://doi.org/10.31234/osf.io/gjvfk](https://doi.org/10.31234/osf.io/gjvfk)
- Bordignon, F., Chaignon, L., & Egret, D. (2023). Promoting narrative CVs to improve research evaluation? A review of opinion pieces and experiments. *Research Evaluation, 32*(2), 313–320. [https://doi.org/10.1093/reseval/rvad013](https://doi.org/10.1093/reseval/rvad013)
- Boury, H., Albert, M., Chen, R. H. C., Chow, J. C. L., DaCosta, R., Hoffman, M. M., Keshavarz, B., Kontos, P., McAndrews, M. P., Protze, S., & Gagliardi, A. R. (2023). Exploring the merits of research performance measures that comply with the San Francisco Declaration on Research Assessment and strategies to overcome barriers of adoption: Qualitative interviews with administrators and researchers. *Health Research Policy and Systems, 21*(1), 43. [https://doi.org/10.1186/s12961-023-01001-w](https://doi.org/10.1186/s12961-023-01001-w)
- Brandmaier, A. M., Ernst, M. S., & Peikert, A. (2023). Assessing rigor and impact of research software for hiring and promotion in psychology: A comment on Gärtner et al. (2022). *PsyArXiv.* https://doi.org/10.31234/osf.io/kcd82
- Donovan, C. (2011). State of the art in assessing research impact: Introduction to a special issue. *Research Evaluation, 20*(3), 175–179. [https://doi.org/10.3152/095820211x13118583635918](https://doi.org/10.3152/095820211x13118583635918)
- Fedorciow, L., & Bayley, J. (2014). Strategies for the Management and Adoption of Impact Capture Processes within Research Information Management Systems. *Procedia Computer Science, 33*, 25–32. [https://doi.org/10.1016/j.procs.2014.06.005](https://doi.org/10.1016/j.procs.2014.06.005)
- Friesen, F., Baker, L. R., Ziegler, C., Dionne, A., & Ng, S. L. (2019). Approaching Impact Meaningfully in Medical Education Research. *Academic Medicine, 94*(7), 955–961. [https://doi.org/10.1097/acm.0000000000002718](https://doi.org/10.1097/acm.0000000000002718)
- Gagliardi, A. R., Chen, R. H. C., Boury, H., Albert, M., Chow, J., DaCosta, R. S., Hoffman, M., Keshavarz, B., Kontos, P., Liu, J., McAndrews, M. P., & Protze, S. (2023). DORA-compliant measures of research quality and impact to assess the performance of researchers in biomedical institutions: Review of published research, international best practice and Delphi survey. *PLOS ONE, 18*(5), e0270616. [https://doi.org/10.1371/journal.pone.0270616](https://doi.org/10.1371/journal.pone.0270616)
- Gärtner, A., Leising, D., Freyer, N., Musfeld, P., Lange, J., & Schönbrodt, F. D. (2022). Responsible Research Assessment II: A specific proposal for hiring and promotion in psychology. *PsyArXiv.* [https://doi.org/10.31234/osf.io/5yexm](https://doi.org/10.31234/osf.io/5yexm)
- Kucirkova, N. (2023). Commentary on Highly Successful Female Educational Psychologists: Equity and Intersectionality in Success Definitions. *Educational Psychology Review, 35*(1), 7. [https://doi.org/10.1007/s10648-023-09727-3](https://doi.org/10.1007/s10648-023-09727-3)
- Lawson, C., & Morales Tirado, M. (2023). LinkedIn use by academics: An indicator for science policy and research? *27th International Conference on Science, Technology and Innovation Indicators (STI 2023).* [https://doi.org/10.55835/6442eb73213d7f5155a70585](https://doi.org/10.55835/6442eb73213d7f5155a70585)
- Lim, M. A. (2019). Impact case studies: What accounts for the need for numbers in impact evaluation? *International Studies in Sociology of Education, 29*(1–2), 107–125. [https://doi.org/10.1080/09620214.2019.1624591](https://doi.org/10.1080/09620214.2019.1624591)
- Pitrolino, K., Samarasinghe, B., Pringle, A., & Viney, I. (2024). Identifying stakeholder preferences for communicating impact from medical research: A mixed methods study. *BMC Health Services Research, 24*(1), 1305. [https://doi.org/10.1186/s12913-024-11664-y](https://doi.org/10.1186/s12913-024-11664-y)
- Recio-Saucedo, A., Meadmore, K., & Ribeiro, A. (2024). Narrator: preparatioN, Assessment and use of impact plans in NIHR standaRd ApplicaTion fORms. Study report. *NIHR Open Research, 4*, 3. [https://doi.org/10.3310/nihropenres.1115221.1](https://doi.org/10.3310/nihropenres.1115221.1)
- Torres-Salinas, D., Orduña-Malea, E., Delgado-Vázquez, Á., Gorraiz, J., & Arroyo-Machado, W. (2024). Foundations of Narrative Bibliometrics. *Journal of Informetrics, 18*(3), 101546. [https://doi.org/10.1016/j.joi.2024.101546](https://doi.org/10.1016/j.joi.2024.101546)
- Ulpts, S. (2023). Responsible assessment of what research? Beware of epistemic diversity! *PsyArXiv.* [https://doi.org/10.31234/osf.io/t7zcg](https://doi.org/10.31234/osf.io/t7zcg)
- Witchel, H. J. (2022). Interdisciplinary Research in Physiology: Insights into the Physiological Society’s (UK) Report on “The Future of Interdisciplinary Research beyond REF 2021.” *The FASEB Journal, 36*(S1). [https://doi.org/10.1096/fasebj.2022.36.s1.r2687](https://doi.org/10.1096/fasebj.2022.36.s1.r2687)
- Wu, C. (2023). The gender citation gap: Why and how it matters. *Canadian Review of Sociology/Revue Canadienne de Sociologie, 60*(2), 188–211. [https://doi.org/10.1111/cars.12428](https://doi.org/10.1111/cars.12428)

## Other resources
**PEP-CV**: The Peer Exchange Platform for Narrative-style CVs (PEP-CV) is a resource for the research and innovation community developed by a partnership between funding agencies and researchers. [https://pep-cv.mariecuriealumni.eu](link)


# Comments/lived examples 
***TBD***