---
title: "Making all science anonymous"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Value process", "Aim: Recognition", "Aim: Collaboration", "Aim: Alternative questions", "CoARA Commitment 6", "Target: Funder", "Target: Academic Institution", "Target: Individual scholar", "Target: Meta-Researcher", "Target: Editor and publisher"]
description: "Dropping all names from research proposals, research outputs, etc. so that science becomes a common and community-driven initiatve, with no individual reputational goals or gain."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

- Remove perverse incentives for individual career advancement
- Foster real and complete collaboration
- Make science open and shared as a default

:::

## Research domains

This idea is probably beyond the possibilities of current research assessment systems, but may serve as an interesting thoght experiment to question the individually-centred culture of academic careers, funding, and recognition. 

## Context and considerations

## Challenges and mitigations

## Evaluating success

## Related CoARA commitments

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 

## Case examples and literature

## Other resources

Neuroskeptic. (2013). Anonymity in science. *Trends in Cognitive Sciences*, 17(5), 195–196.[https://doi.org/https://doi.org/10.1016/j.tics.2013.03.004](https://doi.org/https://doi.org/10.1016/j.tics.2013.03.004)

Background arguments can also be found in Frazzetto, G. (2004). Who did what? Uneasiness with the current authorship is prompting the scientific community to seek alternatives. *EMBO Reports*, 5(5), 446–448. [https://doi.org/10.1038/sj.embor.7400161](https://doi.org/10.1038/sj.embor.7400161 )

# Comments/lived examples

