---
title: "Community impact evaluation"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Inclusivity", "Aim: Value process", "Aim: Collaboration", "Aim: Alternative questions", "Target: Academic institution", "Target: Funder", "Target: Research group", "Target: Individual scholar", "CoARA Commitment 1", "CoARA Commitment 5", "CoARA Commitment 6"]
description: "Asking the communities involved and targeted by the research to be part of the evaluation process can help research funding decisions to better consider the needs of the communities they impact on."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

- Build more targeted approaches to research which consider the needs of the communities they impact on. 

:::

## Research domains

This is especially relevant to research projects that have societal and community impact, with a lesser relevance for completely fundamental research.

## Context and considerations

In this context, assessment panels would involve people from impacted, researched, or supported communities and include them in the evaluation of proposals to ensure that the funded projects are aligned with their needs/interests. This may relate to both potential impact and acutal impact.

## Challenges and mitigations

## Evaluating success

## Related CoARA commitments

# Relevant resources and literature 

## Templates from funders and institutions 

## Case examples and literature

As part of the [Canadian Institute of Health Research (CIHR) Action Plan: Building a healthier future for First Nations, Inuit, and Métis Peoples](https://cihr-irsc.gc.ca/e/50372.html), a [Reference Group on Indigenous Health Research](https://cihr-irsc.gc.ca/e/52822.html) was established to co-developed a strategic plan addressing different aspects of the research funding agency. Part of this plan includes a set of guiding principles for the appropriate review of Indigenous research and ways to implement iterative peer review processes for applications relevant to Indigenous health. 

## Other resources

# Comments/lived examples

