---
title: "Non-expert panels"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Inclusivity", "Aim: Value process", "Aim: Collaboration", "Aim: Alternative questions", "Target: Academic institution", "Target: Funder", "Target: Research group", "Target: Individual scholar", "CoARA Commitment 1", "CoARA Commitment 6"]
description: "Replacing or supplementing existing panels with non-researchers, to evaluate aspects of the proposal (or the object of the evaluation) that are not directly research related."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

:::

## Research domains

## Context and considerations

This could be focused on aspects such as economic potential, leadership and management competences, usibility of outputs, or other elements that are valued in the assessment. Connected ideas of **[Community impact assessment](../community-impact-evaluation/index.qmd)** or **[Research users impacted as evaluators](../research-users-impacted-as-evaluators/index.qmd)** can be ways of undertaking this, but this idea can expand beyond direct users and impacted communities to address different aspects of the proposal and application material.

## Challenges and mitigations

## Evaluating success

## Related CoARA commitments

CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes

# Relevant resources and literature 

## Templates from funders and institutions 

## Case examples and literature

Several funders include members of the public in their review panels. See this example from **[Health Research Board Ireland](https://www.hrb.ie/funding/responsible-research-assessment/public-and-patient-involvement-in-research/ppi-information-for-the-public/)** which explains what it entails to be public participants to the review panel.

## Other resources

# Case Studies or Implementation Examples

