---
title: "Reflective evaluation – self-driven criteria creation"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Value process", "Aim: Alternative questions", "Aim: Recognition", "Aim: Diversity", "Target: Academic Institution", "Target: Research Group", "Target: Individual scholar", "CoARA Commitment 1", "CoARA Commitment 6"]
]
description: "Allow the person/group being evaluated to set criteria for their own evaluation, and give a self-reflection on their progress towards those criteria. This can be used in both reporting/progress evaluation as well as in pre-decision evaluation."
image: false
---

::: {.callout-warning icon=false}

## Objectives and potential outcome

:::

## Research domains

This idea is especially relevant for career progression assessment, although it could be implemented to a broad diversity of assessment where individuals or groups are central to the assessment process.

## Context and considerations

This idea reflects one of the core element of the SCOPE Framework (see [related idea](https://eui-library.github.io/coara-idea-catalogue/ideas/scope-framework/index.html)). 

## Challenges and mitigations

**Challenge:** Possibility of bias of the evaluation criteria selected by applicants to favour a positive assessment (i.e., based on current strengths rather than on real values).  
**Mitigation:** Building an in-depth criteria setting activity that looks at values could help support more deliberate and value-based assessment (see [associated idea](https://eui-library.github.io/coara-idea-catalogue/ideas/valuebased-assessment/index.html)). For shared assessment criteria, involving multiple individuals in deciding assessment processes and criteria can also help circumvent this challenge as it would allow individuals to come to a shared agreement on what the value and what is important to them. Nevertheless, allowing for a plurality of assessment can also have advantages in promoting diversity and meaningfulness.  
**Mitigation:** Another mitigation may be to get individuals to set assessment criteria as goals, pushing and motivating them towards future skills, achievements, and performances that are valuable to them. The idea on9forward-looking assessment](https://eui-library.github.io/coara-idea-catalogue/ideas/forward-looking-assessment/index.html) contains more details on this, including examples from some organisations who already undertake these self-defined goals in their promotion processes. 

## Evaluating success

## Related CoARA commitments

CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 

## Case examples and literature

## Other resources

# Case Studies or Implementation Examples

