---
title: "Application burden proportional to money/reward"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Value process", "Aim: Alternative questions", "CoARA Commitment 6", "Target: Funder", "Target: Academic institution", "Target: Scholarly association"]
description: "Modifying the length and complexity of the application process based on the funding volume/award/result of the process can help reduce application burden. For larger grants/more senior positions, a more intense application process may be justified, but for small grants/short term applications, a light application process is preferable. This will reduce the burden for applicants, evaluators, and the organisations in charge of the assessment."
image: false
---

<!--
GENERAL GUIDELINES:
- Use this guide to style all text: https://quarto.org/docs/authoring/markdown-basics.html
- Tags (apply as relevant):
Level 0 = Level of completeness: 0 – The experiment only contains the description and minimal details. This level is meant to provide inspiration for experiments that can be developed further by those experimenting.
Level 1 = Level of completeness: 1 –  The experiment contains minimal details. Organisations will need to build the experimentation plan before they can implement the idea.
Level 2 = Level of completeness: 2 – The experiment contains minimal details that may help with the design and implementation, but organisations will need to build most of the experimentation plan before they can fully implement the idea.
Level 3 = Level of completeness: 3 – The experiment contains some details that may help with the design and implementation, but organisations will need to finalise the experimentation plan before they can fully implement the idea.
Level 4 = Level of completeness: 4 – The experiment contains details that can provide useful guidance for implementation, but additional research will need to be done by experimenting organisation. Few real life cases exist.
Level 5 = Level of completeness: 5 – The experiment contains sufficient details to be implemented, and it has already been experimented in some organisations providing cases, additional suggestions, and often learned lessons.
Aim: Value process = Create an assessment process based upon what the different players in research value
Aim: Inclusivity = Make research more inclusive and equitable through assessment
Aim: Bias mitigation = Mitigate the negative effects of bias on assessment
Aim: Recognition = Recognize process and culture through assessment
Aim: Diversity = Foster diversity through assessment
Aim: Collaboration = Foster collaboration through assessment
Aim: Alternative questions = Ask assessment questions differently
CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 = Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 3 = Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index
CoARA Commitment 4 = Avoid the use of rankings of research organisations in research assessment
CoARA Commitment 5 = Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 = Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 = Exchange practices and experiences to enable mutual learning within and beyond the Coalition
CoARA Commitment 9 = Communicate progress made on adherence to the Principles and implementation of the Commitments
CoARA Commitment 10 = Evaluate practices, criteria and tools based on solid evidence and the state-of-the-art in research on research, and make data openly available for evidence gathering and research
User: Funders = Target user could involve funding agencies and regional authorities
User: Academic Institutions = Target user could involve research institutions, higher education institutions, and research performing organisations
User: Scholarly associations = Target user could involve academies, scholarly associations, and learned societies
User: Research Groups = Target user could involve Research groups
User: Individual scholar = Target user could involve individual scholars, including researchers, research students, or research staff
User: Meta-Researchers = Target user could involve Meta-researchers
User: Editors and publishers = Target user could involve scientific editors and publishers
-->

::: {.callout-warning icon=false}

## Objectives and potential outcome
<!--
PROMPTS:
- What happens if this is successful? What changes if this works? 
- What improvements are we aiming for?
- These can be related to the main questions
- If there are multiple experiments fitting, put them here
-->
This idea aims to reduce the application burden that happens for applicants, reviewers, and organisations, wherever possible.
- **Reduce unnecessary burden** for small application processes
- **Make more efficient use of research time and resources**
- Less time/resources spent on small research assessment can increase assessment capacity and indirectly **increase assessment quality** where it is really needed

:::

## Research domains
<!--
PROMPTS:
- Which domain(s) can this experiment be applied in? 
-->

This idea is relevant to research funders in particular, but it may be relevant to any types of assessment and application processes. These may include hiring and promotion processes, awards submission processes, funding or fellowship applications, etc.   

## Context and considerations
<!--
PROMPTS:
- Who is carrying out the evaluation? Who is this experiment for? (i.e., Target groups - Funders? Institutions? Individual researchers? Research domains?); 
- What type of assessment does this work on (Team/individual/project/institutional);
- What is the objective of evaluation exercise linked to the type of assessment
- What are the things that change in the experiment?
- Nature of the organization carrying out evaluation exercise; What type of assessment (Team/individual/project/institutional); Objective of evaluation exercise linked to the type of assessment
-->

Application processes take time and resources, regardless of the outcome. In fact, several studies have shown that the costs of application to grant proposal is non negligeable, and that their costs can even exceed the awarded funding that is redistributed in research (see [Herbert et al., (2013)](https://doi.org/10.1136/bmjopen-2013-002800); [Gross and Bergstrom (2019)](https://doi.org/10.1371/journal.pbio.3000065); [Schweiger (2025)](https://doi.org/10.1038/d41586-025-04060-x)).   
  
While the calculation of funding value is complex and funding investments in research are believed to build value at much higher rates than initial investments (see [Stafford (2026)](https://doi.org/10.1038/d41586-026-00498-9)), building application processes with a burden proportional to the success value would help shape more efficient assessment process, enabling to free up time and resources for high quality assessment processes. 

## Challenges and mitigations
<!--
PROMPTS:
- Each challenge and mitigation grouped together
- If there isn’t mitigation, say so
- Tips and tricks for preparing and running the experiment
-->


## Evaluating success
<!--
PROMPTS:
- Evaluation criteria for the experiment 
- How do you know it worked or didn’t?
-->


## Related CoARA commitments
<!--
PROMPTS:
Directly reference as many of the 10 CoARA commitments as are fitting
-->

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 
<!--
PROMPTS:
- Add templates from funders and institutions if existing
-->

## Case examples and literature
<!--
PROMPTS:
Any organisation names, links, authors that may be relevant to look into
-->

## Other resources
<!--
PROMPTS:
Include any other resource here
-->

Fackrell K, Church H, Crane K, et al Online survey exploring researcher experiences of research funding processes in the UK: the effort and burden of applying for funding and fulfilling reporting requirements BMJ Open 2024;14:e079581. doi: [10.1136/bmjopen-2023-079581](https://10.1136/bmjopen-2023-079581)


# Comments/lived examples
<!--
PROMPTS:
Section to be kept blank, for input within the idea catalogue
-->




