---
title: "Forward looking assessment"
author: "Experiments in Assessment WG"
date: 2026-04-09
date-modified: last-modified
categories: ["Level 0", "Aim: Value process", "Aim: Alternative questions", "Aim: Recognition", "Aim: Diversity", "Target: Academic Institution", "Target: Research Group", "Target: Funder", "Target: Individual scholar", "CoARA Commitment 1", "CoARA Commitment 3", "CoARA Commitment 4"]
description: "Career assessment focusing on future activities and potential rather than track record and what has been done already."
image: false
---

<!--
GENERAL GUIDELINES:
- Use this guide to style all text: https://quarto.org/docs/authoring/markdown-basics.html
- Tags (apply as relevant):
Level 0 = Level of completeness: 0 – The experiment only contains the description and minimal details. This level is meant to provide inspiration for experiments that can be developed further by those experimenting.
Level 1 = Level of completeness: 1 –  The experiment contains minimal details. Organisations will need to build the experimentation plan before they can implement the idea.
Level 2 = Level of completeness: 2 – The experiment contains minimal details that may help with the design and implementation, but organisations will need to build most of the experimentation plan before they can fully implement the idea.
Level 3 = Level of completeness: 3 – The experiment contains some details that may help with the design and implementation, but organisations will need to finalise the experimentation plan before they can fully implement the idea.
Level 4 = Level of completeness: 4 – The experiment contains details that can provide useful guidance for implementation, but additional research will need to be done by experimenting organisation. Few real life cases exist.
Level 5 = Level of completeness: 5 – The experiment contains sufficient details to be implemented, and it has already been experimented in some organisations providing cases, additional suggestions, and often learned lessons.
Aim: Value process = Create an assessment process based upon what the different players in research value
Aim: Inclusivity = Make research more inclusive and equitable through assessment
Aim: Bias mitigation = Mitigate the negative effects of bias on assessment
Aim: Recognition = Recognize process and culture through assessment
Aim: Diversity = Foster diversity through assessment
Aim: Collaboration = Foster collaboration through assessment
Aim: Alternative questions = Ask assessment questions differently
CoARA Commitment 1 = Recognise the diversity of contributions to, and careers in, research in accordance with the needs and nature of the research
CoARA Commitment 2 = Base research assessment primarily on qualitative evaluation for which peer review is central, supported by responsible use of quantitative indicators
CoARA Commitment 3 = Abandon inappropriate uses in research assessment of journal- and publication-based metrics, in particular inappropriate uses of Journal Impact Factor (JIF) and h-index
CoARA Commitment 4 = Avoid the use of rankings of research organisations in research assessment
CoARA Commitment 5 = Commit resources to reforming research assessment as is needed to achieve the organisational changes committed to
CoARA Commitment 6 = Review and develop research assessment criteria, tools and processes
CoARA Commitment 7 = Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
CoARA Commitment 8 = Exchange practices and experiences to enable mutual learning within and beyond the Coalition
CoARA Commitment 9 = Communicate progress made on adherence to the Principles and implementation of the Commitments
CoARA Commitment 10 = Evaluate practices, criteria and tools based on solid evidence and the state-of-the-art in research on research, and make data openly available for evidence gathering and research
Target: Funder = Target user could involve funding agencies and regional authorities
Target: Academic Institution = Target user could involve research institutions, higher education institutions, and research performing organisations
Target: Scholarly association = Target user could involve academies, scholarly associations, and learned societies
Target: Research Group = Target user could involve Research groups
Target: Individual scholar = Target user could involve individual scholars, including researchers, research students, or research staff
Target: Meta-Researcher = Target user could involve Meta-researchers
Target: Editor and publisher = Target user could involve scientific editors and publishers
-->

::: {.callout-warning icon=false}

## Objectives and potential outcome
<!--
PROMPTS:
- What happens if this is successful? What changes if this works? 
- What improvements are we aiming for?
- These can be related to the main questions
- If there are multiple experiments fitting, put them here
-->

- Can allow for development of an individual niche and enable applicants to follow new pathways that could be broader and/or different than traditional ones.
- Gives the applicant room to decide what they would like to accomplish in their career
- Gives the assessors an overview of the goals and perspectives of the applicant beyond previous experience and former settings

:::

## Research domains
<!--
PROMPTS:
- Which domain(s) can this experiment be applied in? 
-->

This idea is especially relevant to career assessment, either hiring or promotion. It is a concept that is generally well applied in research funding applications, but that is not always targeted in hiring and career assessment.  

## Context and considerations
<!--
PROMPTS:
- Who is carrying out the evaluation? Who is this experiment for? (i.e., Target groups - Funders? Institutions? Individual researchers? Research domains?); 
- What type of assessment does this work on (Team/individual/project/institutional);
- What is the objective of evaluation exercise linked to the type of assessment
- What are the things that change in the experiment?
- Nature of the organization carrying out evaluation exercise; What type of assessment (Team/individual/project/institutional); Objective of evaluation exercise linked to the type of assessment
-->

This could involve asking candidated to set up a plan for development, activities, and goals, with reflective monitoring and milestone development. It could look similar to a project proposal sent for funding, but aim to propose plans for an applicant's career. Focusing the assessment process on forward and future elements can allow for development of an individual niche and enable them to follow new pathways that could be broader and/or different than traditional ones.  


## Challenges and mitigations
<!--
PROMPTS:
- Each challenge and mitigation grouped together
- If there isn’t mitigation, say so
- Tips and tricks for preparing and running the experiment
-->

**Challenge:** The career and aspirations of a candidates may not be realistic or realised.  
**Mitigation:** Focusing on feasibility of the proposed plan can help assess the possibility of implementing the plans that the assessed would like to pursue. In some cases, having a discussion with the applicant on available resources and infrastructures could help applicants build a more informed and balanced plan before they apply. 

## Evaluating success
<!--
PROMPTS:
- Evaluation criteria for the experiment 
- How do you know it worked or didn’t?
-->


## Related CoARA commitments
<!--
PROMPTS:
Directly reference as many of the 10 CoARA commitments as are fitting
-->

# Relevant resources and literature 

This section includes resources, literature, and reports relevant to this specific experimental idea.

## Templates from funders and institutions 
<!--
PROMPTS:
- Add templates from funders and institutions if existing
-->

## Case examples and literature
<!--
PROMPTS:
Any organisation names, links, authors that may be relevant to look into
-->

Some universities base career promotion on self-determined plans where researchers establish their desired goals and objectives and are assessed on these defined goals later in their career. This is the cade for the Career path and evaluation policy for Professorial Staff (ZAP) at Ghent University, for example (see [here](https://www.ugent.be/plone_portal/en/work/mobility-career/career-aspects/professorial-staff) and [here](https://sfdora.org/resource/ghent-university/)). 

The Dutch Recognition and Reward programme also supports a similar self-defined career path which could enable forward-looking assessments (see [here](https://recognitionrewards.nl/about/position-paper/)).

## Other resources
<!--
PROMPTS:
Include any other resource here
-->


# Comments/lived examples
<!--
PROMPTS:
Section to be kept blank, for input within the idea catalogue
-->



